#include "cnegative/native_runtime.h"

#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif

const char *cn_backend_ipc_runtime_source(void) {
    return
        "#ifndef _WIN32\n"
        "#define _POSIX_C_SOURCE 200809L\n"
        "#endif\n"
        "#include <stdint.h>\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n"
        "#ifdef _WIN32\n"
        "#include <windows.h>\n"
        "#else\n"
        "#include <errno.h>\n"
        "#include <signal.h>\n"
        "#include <sys/types.h>\n"
        "#include <sys/wait.h>\n"
        "#include <unistd.h>\n"
        "#endif\n"
        "\n"
        "typedef struct cn_std_ipc_child {\n"
        "    void *handle;\n"
        "} cn_std_ipc_child;\n"
        "\n"
        "#ifdef _WIN32\n"
        "typedef struct cn_ipc_state {\n"
        "    PROCESS_INFORMATION process;\n"
        "    HANDLE stdin_write;\n"
        "    HANDLE stdout_read;\n"
        "    HANDLE stderr_read;\n"
        "    int waited;\n"
        "    int64_t exit_code;\n"
        "} cn_ipc_state;\n"
        "#else\n"
        "typedef struct cn_ipc_state {\n"
        "    pid_t pid;\n"
        "    int stdin_write;\n"
        "    int stdout_read;\n"
        "    int stderr_read;\n"
        "    int waited;\n"
        "    int64_t exit_code;\n"
        "} cn_ipc_state;\n"
        "#endif\n"
        "\n"
        "#ifdef _WIN32\n"
        "static int cn_ipc_append_char(char **buffer, size_t *length, size_t *capacity, char ch) {\n"
        "    if (*length + 2 > *capacity) {\n"
        "        size_t next = *capacity == 0 ? 64 : (*capacity * 2);\n"
        "        while (*length + 2 > next) {\n"
        "            next *= 2;\n"
        "        }\n"
        "        char *grown = (char *)realloc(*buffer, next);\n"
        "        if (grown == NULL) {\n"
        "            return 0;\n"
        "        }\n"
        "        *buffer = grown;\n"
        "        *capacity = next;\n"
        "    }\n"
        "    (*buffer)[*length] = ch;\n"
        "    *length += 1;\n"
        "    (*buffer)[*length] = '\\0';\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "static int cn_ipc_append_text(char **buffer, size_t *length, size_t *capacity, const char *text) {\n"
        "    if (text == NULL) {\n"
        "        return 1;\n"
        "    }\n"
        "    while (*text != '\\0') {\n"
        "        if (!cn_ipc_append_char(buffer, length, capacity, *text)) {\n"
        "            return 0;\n"
        "        }\n"
        "        text += 1;\n"
        "    }\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "static int cn_ipc_append_quoted_windows_arg(char **buffer, size_t *length, size_t *capacity, const char *arg) {\n"
        "    const char *cursor = arg == NULL ? \"\" : arg;\n"
        "    const char *special = strpbrk(cursor, \" \\t\\\"\");\n"
        "    int needs_quotes = (*cursor == '\\0') || (special != NULL);\n"
        "    if (!needs_quotes) {\n"
        "        return cn_ipc_append_text(buffer, length, capacity, cursor);\n"
        "    }\n"
        "    if (!cn_ipc_append_char(buffer, length, capacity, '\"')) {\n"
        "        return 0;\n"
        "    }\n"
        "    while (*cursor != '\\0') {\n"
        "        size_t slashes = 0;\n"
        "        while (cursor[slashes] == '\\\\') {\n"
        "            slashes += 1;\n"
        "        }\n"
        "        if (cursor[slashes] == '\\0') {\n"
        "            size_t i = 0;\n"
        "            while (i < slashes * 2) {\n"
        "                if (!cn_ipc_append_char(buffer, length, capacity, '\\\\')) {\n"
        "                    return 0;\n"
        "                }\n"
        "                i += 1;\n"
        "            }\n"
        "            break;\n"
        "        }\n"
        "        if (cursor[slashes] == '\"') {\n"
        "            size_t i = 0;\n"
        "            while (i < slashes * 2 + 1) {\n"
        "                if (!cn_ipc_append_char(buffer, length, capacity, '\\\\')) {\n"
        "                    return 0;\n"
        "                }\n"
        "                i += 1;\n"
        "            }\n"
        "            if (!cn_ipc_append_char(buffer, length, capacity, '\"')) {\n"
        "                return 0;\n"
        "            }\n"
        "            cursor += slashes + 1;\n"
        "            continue;\n"
        "        }\n"
        "        while (slashes > 0) {\n"
        "            if (!cn_ipc_append_char(buffer, length, capacity, '\\\\')) {\n"
        "                return 0;\n"
        "            }\n"
        "            slashes -= 1;\n"
        "        }\n"
        "        if (!cn_ipc_append_char(buffer, length, capacity, *cursor)) {\n"
        "            return 0;\n"
        "        }\n"
        "        cursor += 1;\n"
        "    }\n"
        "    return cn_ipc_append_char(buffer, length, capacity, '\"');\n"
        "}\n"
        "\n"
        "static char *cn_ipc_build_windows_command_line(const char *program, const char *const *args, int64_t arg_count) {\n"
        "    char *buffer = NULL;\n"
        "    size_t length = 0;\n"
        "    size_t capacity = 0;\n"
        "    int64_t index = 0;\n"
        "    if (!cn_ipc_append_quoted_windows_arg(&buffer, &length, &capacity, program)) {\n"
        "        free(buffer);\n"
        "        return NULL;\n"
        "    }\n"
        "    while (index < arg_count) {\n"
        "        if (!cn_ipc_append_char(&buffer, &length, &capacity, ' ')) {\n"
        "            free(buffer);\n"
        "            return NULL;\n"
        "        }\n"
        "        if (!cn_ipc_append_quoted_windows_arg(&buffer, &length, &capacity, args[index])) {\n"
        "            free(buffer);\n"
        "            return NULL;\n"
        "        }\n"
        "        index += 1;\n"
        "    }\n"
        "    return buffer;\n"
        "}\n"
        "#endif\n"
        "\n"
        "static cn_std_ipc_child *cn_ipc_wrap_child(cn_ipc_state *state) {\n"
        "    cn_std_ipc_child *child = (cn_std_ipc_child *)malloc(sizeof(cn_std_ipc_child));\n"
        "    if (child == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    child->handle = state;\n"
        "    return child;\n"
        "}\n"
        "\n"
        "static cn_ipc_state *cn_ipc_unwrap_state(cn_std_ipc_child *child) {\n"
        "    if (child == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return (cn_ipc_state *)child->handle;\n"
        "}\n"
        "\n"
        "#ifdef _WIN32\n"
        "static void cn_ipc_close_handle(HANDLE *handle) {\n"
        "    if (handle != NULL && *handle != NULL && *handle != INVALID_HANDLE_VALUE) {\n"
        "        CloseHandle(*handle);\n"
        "        *handle = NULL;\n"
        "    }\n"
        "}\n"
        "\n"
        "void *cn_ipc_native_spawn(const char *program, const char *const *args, int64_t arg_count) {\n"
        "    SECURITY_ATTRIBUTES attrs;\n"
        "    HANDLE stdin_read = NULL;\n"
        "    HANDLE stdin_write = NULL;\n"
        "    HANDLE stdout_read = NULL;\n"
        "    HANDLE stdout_write = NULL;\n"
        "    HANDLE stderr_read = NULL;\n"
        "    HANDLE stderr_write = NULL;\n"
        "    STARTUPINFOA startup;\n"
        "    PROCESS_INFORMATION process;\n"
        "    cn_ipc_state *state = NULL;\n"
        "    cn_std_ipc_child *child = NULL;\n"
        "    char *command_line = NULL;\n"
        "\n"
        "    if (program == NULL || *program == '\\0') {\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    ZeroMemory(&attrs, sizeof(attrs));\n"
        "    attrs.nLength = sizeof(attrs);\n"
        "    attrs.bInheritHandle = TRUE;\n"
        "\n"
        "    if (!CreatePipe(&stdin_read, &stdin_write, &attrs, 0)) {\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!SetHandleInformation(stdin_write, HANDLE_FLAG_INHERIT, 0)) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!CreatePipe(&stdout_read, &stdout_write, &attrs, 0)) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!SetHandleInformation(stdout_read, HANDLE_FLAG_INHERIT, 0)) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stdout_write);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!CreatePipe(&stderr_read, &stderr_write, &attrs, 0)) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stdout_write);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!SetHandleInformation(stderr_read, HANDLE_FLAG_INHERIT, 0)) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stdout_write);\n"
        "        cn_ipc_close_handle(&stderr_read);\n"
        "        cn_ipc_close_handle(&stderr_write);\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    command_line = cn_ipc_build_windows_command_line(program, args, arg_count);\n"
        "    if (command_line == NULL) {\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stdout_write);\n"
        "        cn_ipc_close_handle(&stderr_read);\n"
        "        cn_ipc_close_handle(&stderr_write);\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    ZeroMemory(&startup, sizeof(startup));\n"
        "    startup.cb = sizeof(startup);\n"
        "    startup.dwFlags = STARTF_USESTDHANDLES;\n"
        "    startup.hStdInput = stdin_read;\n"
        "    startup.hStdOutput = stdout_write;\n"
        "    startup.hStdError = stderr_write;\n"
        "\n"
        "    ZeroMemory(&process, sizeof(process));\n"
        "    if (!CreateProcessA(NULL, command_line, NULL, NULL, TRUE, 0, NULL, NULL, &startup, &process)) {\n"
        "        free(command_line);\n"
        "        cn_ipc_close_handle(&stdin_read);\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stdout_write);\n"
        "        cn_ipc_close_handle(&stderr_read);\n"
        "        cn_ipc_close_handle(&stderr_write);\n"
        "        return NULL;\n"
        "    }\n"
        "    free(command_line);\n"
        "    cn_ipc_close_handle(&stdin_read);\n"
        "    cn_ipc_close_handle(&stdout_write);\n"
        "    cn_ipc_close_handle(&stderr_write);\n"
        "    CloseHandle(process.hThread);\n"
        "\n"
        "    state = (cn_ipc_state *)malloc(sizeof(cn_ipc_state));\n"
        "    if (state == NULL) {\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stderr_read);\n"
        "        CloseHandle(process.hProcess);\n"
        "        return NULL;\n"
        "    }\n"
        "    state->process = process;\n"
        "    state->stdin_write = stdin_write;\n"
        "    state->stdout_read = stdout_read;\n"
        "    state->stderr_read = stderr_read;\n"
        "    state->waited = 0;\n"
        "    state->exit_code = 0;\n"
        "    child = cn_ipc_wrap_child(state);\n"
        "    if (child == NULL) {\n"
        "        cn_ipc_close_handle(&stdin_write);\n"
        "        cn_ipc_close_handle(&stdout_read);\n"
        "        cn_ipc_close_handle(&stderr_read);\n"
        "        CloseHandle(process.hProcess);\n"
        "        free(state);\n"
        "        return NULL;\n"
        "    }\n"
        "    return child;\n"
        "}\n"
        "\n"
        "static char *cn_ipc_read_handle(HANDLE handle, int64_t max_bytes) {\n"
        "    char *buffer;\n"
        "    DWORD read_count = 0;\n"
        "    if (handle == NULL || handle == INVALID_HANDLE_VALUE || max_bytes <= 0) {\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer = (char *)malloc((size_t)max_bytes + 1);\n"
        "    if (buffer == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    if (!ReadFile(handle, buffer, (DWORD)max_bytes, &read_count, NULL)) {\n"
        "        DWORD error = GetLastError();\n"
        "        free(buffer);\n"
        "        if (error == ERROR_BROKEN_PIPE) {\n"
        "            return NULL;\n"
        "        }\n"
        "        return NULL;\n"
        "    }\n"
        "    if (read_count == 0) {\n"
        "        free(buffer);\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer[read_count] = '\\0';\n"
        "    return buffer;\n"
        "}\n"
        "\n"
        "static char *cn_ipc_read_line_handle(HANDLE handle, int64_t max_bytes) {\n"
        "    char *buffer;\n"
        "    DWORD read_count = 0;\n"
        "    int64_t length = 0;\n"
        "    char ch = '\\0';\n"
        "    if (handle == NULL || handle == INVALID_HANDLE_VALUE || max_bytes <= 0) {\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer = (char *)malloc((size_t)max_bytes + 1);\n"
        "    if (buffer == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    while (length < max_bytes) {\n"
        "        if (!ReadFile(handle, &ch, 1, &read_count, NULL)) {\n"
        "            DWORD error = GetLastError();\n"
        "            if (error == ERROR_BROKEN_PIPE) {\n"
        "                read_count = 0;\n"
        "                break;\n"
        "            }\n"
        "            free(buffer);\n"
        "            return NULL;\n"
        "        }\n"
        "        if (read_count == 0) {\n"
        "            break;\n"
        "        }\n"
        "        if (ch == '\\n') {\n"
        "            break;\n"
        "        }\n"
        "        buffer[length] = ch;\n"
        "        length += 1;\n"
        "    }\n"
        "    if (length == 0 && read_count == 0) {\n"
        "        free(buffer);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (length > 0 && buffer[length - 1] == '\\r') {\n"
        "        length -= 1;\n"
        "    }\n"
        "    buffer[length] = '\\0';\n"
        "    return buffer;\n"
        "}\n"
        "\n"
        "int64_t cn_ipc_native_stdin_write(void *raw_child, const char *value) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    DWORD written = 0;\n"
        "    size_t length;\n"
        "    if (state == NULL || state->stdin_write == NULL || state->stdin_write == INVALID_HANDLE_VALUE || value == NULL) {\n"
        "        return -1;\n"
        "    }\n"
        "    length = strlen(value);\n"
        "    if (length == 0) {\n"
        "        return 0;\n"
        "    }\n"
        "    if (!WriteFile(state->stdin_write, value, (DWORD)length, &written, NULL)) {\n"
        "        return -1;\n"
        "    }\n"
        "    return (int64_t)written;\n"
        "}\n"
        "\n"
        "int64_t cn_ipc_native_stdin_write_line(void *raw_child, const char *value) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    DWORD written = 0;\n"
        "    DWORD newline_written = 0;\n"
        "    size_t length;\n"
        "    static const char newline[] = \"\\n\";\n"
        "    if (state == NULL || state->stdin_write == NULL || state->stdin_write == INVALID_HANDLE_VALUE || value == NULL) {\n"
        "        return -1;\n"
        "    }\n"
        "    length = strlen(value);\n"
        "    if (length > 0) {\n"
        "        if (!WriteFile(state->stdin_write, value, (DWORD)length, &written, NULL)) {\n"
        "            return -1;\n"
        "        }\n"
        "    }\n"
        "    if (!WriteFile(state->stdin_write, newline, 1, &newline_written, NULL)) {\n"
        "        return -1;\n"
        "    }\n"
        "    return (int64_t)written + (int64_t)newline_written;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_stdin_close(void *raw_child) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL || state->stdin_write == NULL || state->stdin_write == INVALID_HANDLE_VALUE) {\n"
        "        return 0;\n"
        "    }\n"
        "    CloseHandle(state->stdin_write);\n"
        "    state->stdin_write = NULL;\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stdout_read(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_handle(state->stdout_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stdout_read_line(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_line_handle(state->stdout_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stderr_read(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_handle(state->stderr_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stderr_read_line(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_line_handle(state->stderr_read, max_bytes);\n"
        "}\n"
        "\n"
        "int cn_ipc_native_wait(void *raw_child, int64_t *out_status) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    DWORD status = 0;\n"
        "    if (state == NULL || out_status == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    if (!state->waited) {\n"
        "        if (WaitForSingleObject(state->process.hProcess, INFINITE) != WAIT_OBJECT_0) {\n"
        "            return 0;\n"
        "        }\n"
        "        if (!GetExitCodeProcess(state->process.hProcess, &status)) {\n"
        "            return 0;\n"
        "        }\n"
        "        state->exit_code = (int64_t)(int32_t)status;\n"
        "        state->waited = 1;\n"
        "    }\n"
        "    *out_status = state->exit_code;\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_kill(void *raw_child) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    if (!TerminateProcess(state->process.hProcess, 1)) {\n"
        "        return 0;\n"
        "    }\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_release(void *raw_child) {\n"
        "    cn_std_ipc_child *child = (cn_std_ipc_child *)raw_child;\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state(child);\n"
        "    if (state == NULL || child == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    cn_ipc_close_handle(&state->stdin_write);\n"
        "    cn_ipc_close_handle(&state->stdout_read);\n"
        "    cn_ipc_close_handle(&state->stderr_read);\n"
        "    cn_ipc_close_handle(&state->process.hProcess);\n"
        "    free(state);\n"
        "    child->handle = NULL;\n"
        "    free(child);\n"
        "    return 1;\n"
        "}\n"
        "#else\n"
        "static void cn_ipc_close_fd(int *fd) {\n"
        "    if (fd != NULL && *fd >= 0) {\n"
        "        close(*fd);\n"
        "        *fd = -1;\n"
        "    }\n"
        "}\n"
        "\n"
        "void *cn_ipc_native_spawn(const char *program, const char *const *args, int64_t arg_count) {\n"
        "    int stdin_pipe[2] = {-1, -1};\n"
        "    int stdout_pipe[2] = {-1, -1};\n"
        "    int stderr_pipe[2] = {-1, -1};\n"
        "    pid_t pid;\n"
        "    cn_ipc_state *state = NULL;\n"
        "    cn_std_ipc_child *child = NULL;\n"
        "\n"
        "    if (program == NULL || *program == '\\0') {\n"
        "        return NULL;\n"
        "    }\n"
        "    if (pipe(stdin_pipe) != 0) {\n"
        "        return NULL;\n"
        "    }\n"
        "    if (pipe(stdout_pipe) != 0) {\n"
        "        cn_ipc_close_fd(&stdin_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdin_pipe[1]);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (pipe(stderr_pipe) != 0) {\n"
        "        cn_ipc_close_fd(&stdin_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdin_pipe[1]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[1]);\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    pid = fork();\n"
        "    if (pid < 0) {\n"
        "        cn_ipc_close_fd(&stdin_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdin_pipe[1]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[1]);\n"
        "        cn_ipc_close_fd(&stderr_pipe[0]);\n"
        "        cn_ipc_close_fd(&stderr_pipe[1]);\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    if (pid == 0) {\n"
        "        char **argv = (char **)malloc((size_t)(arg_count + 2) * sizeof(char *));\n"
        "        int64_t index = 0;\n"
        "        if (argv == NULL) {\n"
        "            _exit(127);\n"
        "        }\n"
        "        argv[0] = (char *)program;\n"
        "        while (index < arg_count) {\n"
        "            argv[index + 1] = (char *)args[index];\n"
        "            index += 1;\n"
        "        }\n"
        "        argv[arg_count + 1] = NULL;\n"
        "\n"
        "        dup2(stdin_pipe[0], 0);\n"
        "        dup2(stdout_pipe[1], 1);\n"
        "        dup2(stderr_pipe[1], 2);\n"
        "\n"
        "        cn_ipc_close_fd(&stdin_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdin_pipe[1]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[0]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[1]);\n"
        "        cn_ipc_close_fd(&stderr_pipe[0]);\n"
        "        cn_ipc_close_fd(&stderr_pipe[1]);\n"
        "\n"
        "        execvp(program, argv);\n"
        "        _exit(errno == ENOENT ? 127 : 126);\n"
        "    }\n"
        "\n"
        "    cn_ipc_close_fd(&stdin_pipe[0]);\n"
        "    cn_ipc_close_fd(&stdout_pipe[1]);\n"
        "    cn_ipc_close_fd(&stderr_pipe[1]);\n"
        "\n"
        "    state = (cn_ipc_state *)malloc(sizeof(cn_ipc_state));\n"
        "    if (state == NULL) {\n"
        "        cn_ipc_close_fd(&stdin_pipe[1]);\n"
        "        cn_ipc_close_fd(&stdout_pipe[0]);\n"
        "        cn_ipc_close_fd(&stderr_pipe[0]);\n"
        "        return NULL;\n"
        "    }\n"
        "\n"
        "    state->pid = pid;\n"
        "    state->stdin_write = stdin_pipe[1];\n"
        "    state->stdout_read = stdout_pipe[0];\n"
        "    state->stderr_read = stderr_pipe[0];\n"
        "    state->waited = 0;\n"
        "    state->exit_code = 0;\n"
        "    child = cn_ipc_wrap_child(state);\n"
        "    if (child == NULL) {\n"
        "        cn_ipc_close_fd(&state->stdin_write);\n"
        "        cn_ipc_close_fd(&state->stdout_read);\n"
        "        cn_ipc_close_fd(&state->stderr_read);\n"
        "        free(state);\n"
        "        return NULL;\n"
        "    }\n"
        "    return child;\n"
        "}\n"
        "\n"
        "static char *cn_ipc_read_fd(int fd, int64_t max_bytes) {\n"
        "    char *buffer;\n"
        "    ssize_t read_count;\n"
        "    if (fd < 0 || max_bytes <= 0) {\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer = (char *)malloc((size_t)max_bytes + 1);\n"
        "    if (buffer == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    read_count = read(fd, buffer, (size_t)max_bytes);\n"
        "    if (read_count <= 0) {\n"
        "        free(buffer);\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer[read_count] = '\\0';\n"
        "    return buffer;\n"
        "}\n"
        "\n"
        "static char *cn_ipc_read_line_fd(int fd, int64_t max_bytes) {\n"
        "    char *buffer;\n"
        "    ssize_t read_count = 0;\n"
        "    int64_t length = 0;\n"
        "    char ch = '\\0';\n"
        "    if (fd < 0 || max_bytes <= 0) {\n"
        "        return NULL;\n"
        "    }\n"
        "    buffer = (char *)malloc((size_t)max_bytes + 1);\n"
        "    if (buffer == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    while (length < max_bytes) {\n"
        "        read_count = read(fd, &ch, 1);\n"
        "        if (read_count == 0) {\n"
        "            break;\n"
        "        }\n"
        "        if (read_count < 0) {\n"
        "            free(buffer);\n"
        "            return NULL;\n"
        "        }\n"
        "        if (ch == '\\n') {\n"
        "            break;\n"
        "        }\n"
        "        buffer[length] = ch;\n"
        "        length += 1;\n"
        "    }\n"
        "    if (length == 0 && read_count == 0) {\n"
        "        free(buffer);\n"
        "        return NULL;\n"
        "    }\n"
        "    if (length > 0 && buffer[length - 1] == '\\r') {\n"
        "        length -= 1;\n"
        "    }\n"
        "    buffer[length] = '\\0';\n"
        "    return buffer;\n"
        "}\n"
        "\n"
        "int64_t cn_ipc_native_stdin_write(void *raw_child, const char *value) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    size_t length;\n"
        "    ssize_t written;\n"
        "    if (state == NULL || state->stdin_write < 0 || value == NULL) {\n"
        "        return -1;\n"
        "    }\n"
        "    length = strlen(value);\n"
        "    if (length == 0) {\n"
        "        return 0;\n"
        "    }\n"
        "    written = write(state->stdin_write, value, length);\n"
        "    if (written < 0) {\n"
        "        return -1;\n"
        "    }\n"
        "    return (int64_t)written;\n"
        "}\n"
        "\n"
        "int64_t cn_ipc_native_stdin_write_line(void *raw_child, const char *value) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    size_t length;\n"
        "    ssize_t written;\n"
        "    ssize_t newline_written;\n"
        "    static const char newline[] = \"\\n\";\n"
        "    if (state == NULL || state->stdin_write < 0 || value == NULL) {\n"
        "        return -1;\n"
        "    }\n"
        "    length = strlen(value);\n"
        "    if (length > 0) {\n"
        "        written = write(state->stdin_write, value, length);\n"
        "        if (written < 0) {\n"
        "            return -1;\n"
        "        }\n"
        "    } else {\n"
        "        written = 0;\n"
        "    }\n"
        "    newline_written = write(state->stdin_write, newline, 1);\n"
        "    if (newline_written < 0) {\n"
        "        return -1;\n"
        "    }\n"
        "    return (int64_t)written + (int64_t)newline_written;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_stdin_close(void *raw_child) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL || state->stdin_write < 0) {\n"
        "        return 0;\n"
        "    }\n"
        "    close(state->stdin_write);\n"
        "    state->stdin_write = -1;\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stdout_read(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_fd(state->stdout_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stdout_read_line(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_line_fd(state->stdout_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stderr_read(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_fd(state->stderr_read, max_bytes);\n"
        "}\n"
        "\n"
        "char *cn_ipc_native_stderr_read_line(void *raw_child, int64_t max_bytes) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return NULL;\n"
        "    }\n"
        "    return cn_ipc_read_line_fd(state->stderr_read, max_bytes);\n"
        "}\n"
        "\n"
        "int cn_ipc_native_wait(void *raw_child, int64_t *out_status) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    int status = 0;\n"
        "    if (state == NULL || out_status == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    if (!state->waited) {\n"
        "        if (waitpid(state->pid, &status, 0) < 0) {\n"
        "            return 0;\n"
        "        }\n"
        "        if (WIFEXITED(status)) {\n"
        "            state->exit_code = (int64_t)WEXITSTATUS(status);\n"
        "        } else if (WIFSIGNALED(status)) {\n"
        "            state->exit_code = (int64_t)(128 + WTERMSIG(status));\n"
        "        } else {\n"
        "            state->exit_code = 128;\n"
        "        }\n"
        "        state->waited = 1;\n"
        "    }\n"
        "    *out_status = state->exit_code;\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_kill(void *raw_child) {\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state((cn_std_ipc_child *)raw_child);\n"
        "    if (state == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    return kill(state->pid, SIGTERM) == 0;\n"
        "}\n"
        "\n"
        "int cn_ipc_native_release(void *raw_child) {\n"
        "    cn_std_ipc_child *child = (cn_std_ipc_child *)raw_child;\n"
        "    cn_ipc_state *state = cn_ipc_unwrap_state(child);\n"
        "    if (state == NULL || child == NULL) {\n"
        "        return 0;\n"
        "    }\n"
        "    cn_ipc_close_fd(&state->stdin_write);\n"
        "    cn_ipc_close_fd(&state->stdout_read);\n"
        "    cn_ipc_close_fd(&state->stderr_read);\n"
        "    if (!state->waited) {\n"
        "        int status = 0;\n"
        "        if (waitpid(state->pid, &status, WNOHANG) > 0) {\n"
        "            state->waited = 1;\n"
        "        }\n"
        "    }\n"
        "    free(state);\n"
        "    child->handle = NULL;\n"
        "    free(child);\n"
        "    return 1;\n"
        "}\n"
        "#endif\n";
}

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
