#include "cnegative/llvm_runtime.h"

#include <stdio.h>

void cn_llvm_emit_runtime_lines(FILE *stream) {
    fputs("%cn_std_x2E_lines__Buffer = type { ptr, i64, i64 }\n", stream);
    fputs(
        "define private i64 @cn_lines_normalize_capacity(i64 %requested) {\n"
        "entry:\n"
        "  %enough = icmp sge i64 %requested, 8\n"
        "  %value = select i1 %enough, i64 %requested, i64 8\n"
        "  ret i64 %value\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private i64 @cn_lines_array_size(i64 %count) {\n"
        "entry:\n"
        "  %item.size.ptr = getelementptr ptr, ptr null, i32 1\n"
        "  %item.size = ptrtoint ptr %item.size.ptr to i64\n"
        "  %bytes = mul i64 %count, %item.size\n"
        "  ret i64 %bytes\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private ptr @cn_lines_dup(ptr %src) {\n"
        "entry:\n"
        "  %len = call i64 @strlen(ptr %src)\n"
        "  %size = add i64 %len, 1\n"
        "  %dst = call ptr @malloc(i64 %size)\n"
        "  %has.dst = icmp ne ptr %dst, null\n"
        "  br i1 %has.dst, label %copy, label %return.null\n"
        "copy:\n"
        "  %copied = call ptr @memcpy(ptr %dst, ptr %src, i64 %size)\n"
        "  ret ptr %dst\n"
        "return.null:\n"
        "  ret ptr null\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private void @cn_lines_free_items(ptr %data, i64 %count) {\n"
        "entry:\n"
        "  %has.data = icmp ne ptr %data, null\n"
        "  %has.count = icmp sgt i64 %count, 0\n"
        "  %guard = and i1 %has.data, %has.count\n"
        "  br i1 %guard, label %loop, label %done\n"
        "loop:\n"
        "  %index = phi i64 [ 0, %entry ], [ %next, %advance ]\n"
        "  %slot = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %value = load ptr, ptr %slot\n"
        "  %has.value = icmp ne ptr %value, null\n"
        "  br i1 %has.value, label %free.value, label %advance\n"
        "free.value:\n"
        "  call void @free(ptr %value)\n"
        "  br label %advance\n"
        "advance:\n"
        "  %next = add i64 %index, 1\n"
        "  %more = icmp slt i64 %next, %count\n"
        "  br i1 %more, label %loop, label %done\n"
        "done:\n"
        "  ret void\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_buffer_ensure(ptr %buffer, i64 %needed) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %load, label %return.err\n"
        "load:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %capacity.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 2\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %capacity = load i64, ptr %capacity.ptr\n"
        "  %enough = icmp sge i64 %capacity, %needed\n"
        "  br i1 %enough, label %return.ok, label %grow\n"
        "grow:\n"
        "  %has.capacity = icmp sgt i64 %capacity, 0\n"
        "  %double = shl i64 %capacity, 1\n"
        "  %base = select i1 %has.capacity, i64 %double, i64 8\n"
        "  %base.enough = icmp sge i64 %base, %needed\n"
        "  %new.capacity = select i1 %base.enough, i64 %base, i64 %needed\n"
        "  %bytes = call i64 @cn_lines_array_size(i64 %new.capacity)\n"
        "  %new.data = call ptr @realloc(ptr %data, i64 %bytes)\n"
        "  %has.new.data = icmp ne ptr %new.data, null\n"
        "  br i1 %has.new.data, label %store, label %return.err\n"
        "store:\n"
        "  store ptr %new.data, ptr %data.ptr\n"
        "  store i64 %new.capacity, ptr %capacity.ptr\n"
        "  br label %return.ok\n"
        "return.ok:\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %value = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %value\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, ptr } @cn_lines_new() {\n"
        "entry:\n"
        "  %result = call { i1, ptr } @cn_lines_with_capacity(i64 8)\n"
        "  ret { i1, ptr } %result\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, ptr } @cn_lines_with_capacity(i64 %capacity) {\n"
        "entry:\n"
        "  %norm = call i64 @cn_lines_normalize_capacity(i64 %capacity)\n"
        "  %buffer.size.ptr = getelementptr %cn_std_x2E_lines__Buffer, ptr null, i32 1\n"
        "  %buffer.size = ptrtoint ptr %buffer.size.ptr to i64\n"
        "  %buffer = call ptr @malloc(i64 %buffer.size)\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %init, label %return.err\n"
        "init:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %capacity.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 2\n"
        "  store ptr null, ptr %data.ptr\n"
        "  store i64 0, ptr %length.ptr\n"
        "  store i64 0, ptr %capacity.ptr\n"
        "  %ensure = call { i1, i1 } @cn_lines_buffer_ensure(ptr %buffer, i64 %norm)\n"
        "  %ensure.ok = extractvalue { i1, i1 } %ensure, 0\n"
        "  br i1 %ensure.ok, label %return.ok, label %free.buffer\n"
        "free.buffer:\n"
        "  call void @free(ptr %buffer)\n"
        "  br label %return.err\n"
        "return.ok:\n"
        "  %ok = insertvalue { i1, ptr } zeroinitializer, i1 true, 0\n"
        "  %value = insertvalue { i1, ptr } %ok, ptr %buffer, 1\n"
        "  ret { i1, ptr } %value\n"
        "return.err:\n"
        "  ret { i1, ptr } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_free(ptr %buffer) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %free.items, label %return.err\n"
        "free.items:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  call void @cn_lines_free_items(ptr %data, i64 %length)\n"
        "  %has.data = icmp ne ptr %data, null\n"
        "  br i1 %has.data, label %do.free.data, label %free.buffer\n"
        "do.free.data:\n"
        "  call void @free(ptr %data)\n"
        "  br label %free.buffer\n"
        "free.buffer:\n"
        "  call void @free(ptr %buffer)\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %value = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %value\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_clear(ptr %buffer) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %clear, label %return.err\n"
        "clear:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  call void @cn_lines_free_items(ptr %data, i64 %length)\n"
        "  store i64 0, ptr %length.ptr\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %value = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %value\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private i64 @cn_lines_length(ptr %buffer) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %load, label %return.zero\n"
        "load:\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  ret i64 %length\n"
        "return.zero:\n"
        "  ret i64 0\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private i64 @cn_lines_capacity(ptr %buffer) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  br i1 %has.buffer, label %load, label %return.zero\n"
        "load:\n"
        "  %capacity.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 2\n"
        "  %capacity = load i64, ptr %capacity.ptr\n"
        "  ret i64 %capacity\n"
        "return.zero:\n"
        "  ret i64 0\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, ptr } @cn_lines_get(ptr %buffer, i64 %index) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  %index.low = icmp sge i64 %index, 0\n"
        "  %guard0 = and i1 %has.buffer, %index.low\n"
        "  br i1 %guard0, label %load, label %return.err\n"
        "load:\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  %index.high = icmp slt i64 %index, %length\n"
        "  br i1 %index.high, label %load.value, label %return.err\n"
        "load.value:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %slot = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %value.raw = load ptr, ptr %slot\n"
        "  %ok = insertvalue { i1, ptr } zeroinitializer, i1 true, 0\n"
        "  %value = insertvalue { i1, ptr } %ok, ptr %value.raw, 1\n"
        "  ret { i1, ptr } %value\n"
        "return.err:\n"
        "  ret { i1, ptr } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_set(ptr %buffer, i64 %index, ptr %value) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  %index.low = icmp sge i64 %index, 0\n"
        "  %guard0 = and i1 %has.buffer, %index.low\n"
        "  br i1 %guard0, label %load, label %return.err\n"
        "load:\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  %index.high = icmp slt i64 %index, %length\n"
        "  br i1 %index.high, label %dup, label %return.err\n"
        "dup:\n"
        "  %copy = call ptr @cn_lines_dup(ptr %value)\n"
        "  %has.copy = icmp ne ptr %copy, null\n"
        "  br i1 %has.copy, label %store, label %return.err\n"
        "store:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %slot = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %old = load ptr, ptr %slot\n"
        "  %has.old = icmp ne ptr %old, null\n"
        "  br i1 %has.old, label %free.old, label %write.new\n"
        "free.old:\n"
        "  call void @free(ptr %old)\n"
        "  br label %write.new\n"
        "write.new:\n"
        "  store ptr %copy, ptr %slot\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %result = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %result\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_insert(ptr %buffer, i64 %index, ptr %value) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  %index.low = icmp sge i64 %index, 0\n"
        "  %guard0 = and i1 %has.buffer, %index.low\n"
        "  br i1 %guard0, label %load, label %return.err\n"
        "load:\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  %index.high = icmp sle i64 %index, %length\n"
        "  br i1 %index.high, label %dup, label %return.err\n"
        "dup:\n"
        "  %copy = call ptr @cn_lines_dup(ptr %value)\n"
        "  %has.copy = icmp ne ptr %copy, null\n"
        "  br i1 %has.copy, label %ensure, label %return.err\n"
        "ensure:\n"
        "  %needed = add i64 %length, 1\n"
        "  %ensure.result = call { i1, i1 } @cn_lines_buffer_ensure(ptr %buffer, i64 %needed)\n"
        "  %ensure.ok = extractvalue { i1, i1 } %ensure.result, 0\n"
        "  br i1 %ensure.ok, label %move.tail, label %free.copy\n"
        "free.copy:\n"
        "  call void @free(ptr %copy)\n"
        "  br label %return.err\n"
        "move.tail:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %tail.count = sub i64 %length, %index\n"
        "  %has.tail = icmp sgt i64 %tail.count, 0\n"
        "  br i1 %has.tail, label %do.move, label %write.new\n"
        "do.move:\n"
        "  %src = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %next.index = add i64 %index, 1\n"
        "  %dst = getelementptr inbounds ptr, ptr %data, i64 %next.index\n"
        "  %tail.bytes = call i64 @cn_lines_array_size(i64 %tail.count)\n"
        "  %moved = call ptr @memmove(ptr %dst, ptr %src, i64 %tail.bytes)\n"
        "  br label %write.new\n"
        "write.new:\n"
        "  %slot = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  store ptr %copy, ptr %slot\n"
        "  store i64 %needed, ptr %length.ptr\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %result = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %result\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_push(ptr %buffer, ptr %value) {\n"
        "entry:\n"
        "  %length = call i64 @cn_lines_length(ptr %buffer)\n"
        "  %result = call { i1, i1 } @cn_lines_insert(ptr %buffer, i64 %length, ptr %value)\n"
        "  ret { i1, i1 } %result\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i1 } @cn_lines_remove(ptr %buffer, i64 %index) {\n"
        "entry:\n"
        "  %has.buffer = icmp ne ptr %buffer, null\n"
        "  %index.low = icmp sge i64 %index, 0\n"
        "  %guard0 = and i1 %has.buffer, %index.low\n"
        "  br i1 %guard0, label %load, label %return.err\n"
        "load:\n"
        "  %data.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 0\n"
        "  %length.ptr = getelementptr inbounds %cn_std_x2E_lines__Buffer, ptr %buffer, i32 0, i32 1\n"
        "  %data = load ptr, ptr %data.ptr\n"
        "  %length = load i64, ptr %length.ptr\n"
        "  %index.high = icmp slt i64 %index, %length\n"
        "  br i1 %index.high, label %free.old, label %return.err\n"
        "free.old:\n"
        "  %slot = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %old = load ptr, ptr %slot\n"
        "  %has.old = icmp ne ptr %old, null\n"
        "  br i1 %has.old, label %do.free.old, label %move.tail\n"
        "do.free.old:\n"
        "  call void @free(ptr %old)\n"
        "  br label %move.tail\n"
        "move.tail:\n"
        "  %last.index = sub i64 %length, 1\n"
        "  %tail.count.full = sub i64 %length, %index\n"
        "  %tail.count = sub i64 %tail.count.full, 1\n"
        "  %has.tail = icmp sgt i64 %tail.count, 0\n"
        "  br i1 %has.tail, label %do.move, label %clear.last\n"
        "do.move:\n"
        "  %src.index = add i64 %index, 1\n"
        "  %src = getelementptr inbounds ptr, ptr %data, i64 %src.index\n"
        "  %dst = getelementptr inbounds ptr, ptr %data, i64 %index\n"
        "  %tail.bytes = call i64 @cn_lines_array_size(i64 %tail.count)\n"
        "  %moved = call ptr @memmove(ptr %dst, ptr %src, i64 %tail.bytes)\n"
        "  br label %clear.last\n"
        "clear.last:\n"
        "  %last.slot = getelementptr inbounds ptr, ptr %data, i64 %last.index\n"
        "  store ptr null, ptr %last.slot\n"
        "  store i64 %last.index, ptr %length.ptr\n"
        "  %ok = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %result = insertvalue { i1, i1 } %ok, i1 true, 1\n"
        "  ret { i1, i1 } %result\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
}
