#include "cnegative/llvm_runtime.h"

void cn_llvm_emit_runtime_parse(FILE *stream) {
    fputs(
        "define private { i1, i1 } @cn_parse_bool(ptr %value) {\n"
        "entry:\n"
        "  %true.ptr = getelementptr inbounds [5 x i8], ptr @.cn.true, i64 0, i64 0\n"
        "  %false.ptr = getelementptr inbounds [6 x i8], ptr @.cn.false, i64 0, i64 0\n"
        "  %cmp.true = call i32 @strcmp(ptr %value, ptr %true.ptr)\n"
        "  %is.true = icmp eq i32 %cmp.true, 0\n"
        "  br i1 %is.true, label %return.true, label %check.false\n"
        "check.false:\n"
        "  %cmp.false = call i32 @strcmp(ptr %value, ptr %false.ptr)\n"
        "  %is.false = icmp eq i32 %cmp.false, 0\n"
        "  br i1 %is.false, label %return.false, label %return.err\n"
        "return.true:\n"
        "  %ok.true = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %value.true = insertvalue { i1, i1 } %ok.true, i1 true, 1\n"
        "  ret { i1, i1 } %value.true\n"
        "return.false:\n"
        "  %ok.false = insertvalue { i1, i1 } zeroinitializer, i1 true, 0\n"
        "  %value.false = insertvalue { i1, i1 } %ok.false, i1 false, 1\n"
        "  ret { i1, i1 } %value.false\n"
        "return.err:\n"
        "  ret { i1, i1 } zeroinitializer\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, i64 } @cn_parse_int(ptr %value) {\n"
        "entry:\n"
        "  %first = load i8, ptr %value\n"
        "  %is.empty = icmp eq i8 %first, 0\n"
        "  br i1 %is.empty, label %return.err, label %setup\n"
        "setup:\n"
        "  %index.slot = alloca i64\n"
        "  %acc.slot = alloca i64\n"
        "  %negative.slot = alloca i1\n"
        "  store i64 0, ptr %index.slot\n"
        "  store i64 0, ptr %acc.slot\n"
        "  store i1 false, ptr %negative.slot\n"
        "  %is.minus = icmp eq i8 %first, 45\n"
        "  br i1 %is.minus, label %sign.minus, label %check.plus\n"
        "sign.minus:\n"
        "  %second.minus.ptr = getelementptr inbounds i8, ptr %value, i64 1\n"
        "  %second.minus = load i8, ptr %second.minus.ptr\n"
        "  %minus.has.digit = icmp ne i8 %second.minus, 0\n"
        "  br i1 %minus.has.digit, label %set.minus, label %return.err\n"
        "set.minus:\n"
        "  store i1 true, ptr %negative.slot\n"
        "  store i64 1, ptr %index.slot\n"
        "  br label %loop\n"
        "check.plus:\n"
        "  %is.plus = icmp eq i8 %first, 43\n"
        "  br i1 %is.plus, label %sign.plus, label %loop\n"
        "sign.plus:\n"
        "  %second.plus.ptr = getelementptr inbounds i8, ptr %value, i64 1\n"
        "  %second.plus = load i8, ptr %second.plus.ptr\n"
        "  %plus.has.digit = icmp ne i8 %second.plus, 0\n"
        "  br i1 %plus.has.digit, label %set.plus, label %return.err\n"
        "set.plus:\n"
        "  store i64 1, ptr %index.slot\n"
        "  br label %loop\n"
        "loop:\n"
        "  %index = load i64, ptr %index.slot\n"
        "  %char.ptr = getelementptr inbounds i8, ptr %value, i64 %index\n"
        "  %char = load i8, ptr %char.ptr\n"
        "  %is.end = icmp eq i8 %char, 0\n"
        "  br i1 %is.end, label %finish, label %check.digit\n"
        "check.digit:\n"
        "  %digit.low = icmp uge i8 %char, 48\n"
        "  %digit.high = icmp ule i8 %char, 57\n"
        "  %is.digit = and i1 %digit.low, %digit.high\n"
        "  br i1 %is.digit, label %accumulate, label %return.err\n"
        "accumulate:\n"
        "  %acc = load i64, ptr %acc.slot\n"
        "  %digit.byte = sub i8 %char, 48\n"
        "  %digit = zext i8 %digit.byte to i64\n"
        "  %mul = mul i64 %acc, 10\n"
        "  %next.acc = add i64 %mul, %digit\n"
        "  store i64 %next.acc, ptr %acc.slot\n"
        "  %next.index = add i64 %index, 1\n"
        "  store i64 %next.index, ptr %index.slot\n"
        "  br label %loop\n"
        "finish:\n"
        "  %acc.final = load i64, ptr %acc.slot\n"
        "  %negative = load i1, ptr %negative.slot\n"
        "  %negated = sub i64 0, %acc.final\n"
        "  %signed = select i1 %negative, i64 %negated, i64 %acc.final\n"
        "  %ok = insertvalue { i1, i64 } zeroinitializer, i1 true, 0\n"
        "  %value.ok = insertvalue { i1, i64 } %ok, i64 %signed, 1\n"
        "  ret { i1, i64 } %value.ok\n"
        "return.err:\n"
        "  ret { i1, i64 } zeroinitializer\n"
        "}\n\n",
        stream
    );
}
