#include "cnegative/llvm_runtime.h"

#ifdef _WIN32
#define CN_LLVM_PATH_SEPARATOR 92
#else
#define CN_LLVM_PATH_SEPARATOR 47
#endif

void cn_llvm_emit_runtime_path(FILE *stream) {
    fprintf(
        stream,
        "define private ptr @cn_path_join(ptr %%left, ptr %%right) {\n"
        "entry:\n"
        "  %%left.len = call i64 @strlen(ptr %%left)\n"
        "  %%right.len = call i64 @strlen(ptr %%right)\n"
        "  %%left.empty = icmp eq i64 %%left.len, 0\n"
        "  br i1 %%left.empty, label %%return.right, label %%check.right.empty\n"
        "return.right:\n"
        "  %%right.copy.result = call ptr @cn_dup_cstr(ptr %%right)\n"
        "  ret ptr %%right.copy.result\n"
        "check.right.empty:\n"
        "  %%right.empty = icmp eq i64 %%right.len, 0\n"
        "  br i1 %%right.empty, label %%return.left, label %%check.sep\n"
        "return.left:\n"
        "  %%left.copy.result = call ptr @cn_dup_cstr(ptr %%left)\n"
        "  ret ptr %%left.copy.result\n"
        "check.sep:\n"
        "  %%left.last.offset = sub i64 %%left.len, 1\n"
        "  %%left.last.ptr = getelementptr inbounds i8, ptr %%left, i64 %%left.last.offset\n"
        "  %%left.last = load i8, ptr %%left.last.ptr\n"
        "  %%left.sep.slash = icmp eq i8 %%left.last, 47\n"
        "  %%left.sep.backslash = icmp eq i8 %%left.last, 92\n"
        "  %%left.sep = or i1 %%left.sep.slash, %%left.sep.backslash\n"
        "  %%right.first = load i8, ptr %%right\n"
        "  %%right.sep.slash = icmp eq i8 %%right.first, 47\n"
        "  %%right.sep.backslash = icmp eq i8 %%right.first, 92\n"
        "  %%right.sep = or i1 %%right.sep.slash, %%right.sep.backslash\n"
        "  %%skip.right = and i1 %%left.sep, %%right.sep\n"
        "  %%add.sep.candidate = xor i1 %%left.sep, true\n"
        "  %%right.sep.not = xor i1 %%right.sep, true\n"
        "  %%add.sep = and i1 %%add.sep.candidate, %%right.sep.not\n"
        "  %%skip.right.i64 = zext i1 %%skip.right to i64\n"
        "  %%add.sep.i64 = zext i1 %%add.sep to i64\n"
        "  %%right.copy.len = sub i64 %%right.len, %%skip.right.i64\n"
        "  %%size.base = add i64 %%left.len, %%right.copy.len\n"
        "  %%size.with.sep = add i64 %%size.base, %%add.sep.i64\n"
        "  %%size = add i64 %%size.with.sep, 1\n"
        "  %%dst = call ptr @malloc(i64 %%size)\n"
        "  %%has.dst = icmp ne ptr %%dst, null\n"
        "  br i1 %%has.dst, label %%copy.left, label %%fallback\n"
        "copy.left:\n"
        "  %%left.copy = call ptr @memcpy(ptr %%dst, ptr %%left, i64 %%left.len)\n"
        "  br i1 %%add.sep, label %%store.sep, label %%copy.right\n"
        "store.sep:\n"
        "  %%sep.ptr = getelementptr inbounds i8, ptr %%dst, i64 %%left.len\n"
        "  store i8 %d, ptr %%sep.ptr\n"
        "  br label %%copy.right\n"
        "copy.right:\n"
        "  %%right.src = getelementptr inbounds i8, ptr %%right, i64 %%skip.right.i64\n"
        "  %%right.dst.offset = add i64 %%left.len, %%add.sep.i64\n"
        "  %%right.dst = getelementptr inbounds i8, ptr %%dst, i64 %%right.dst.offset\n"
        "  %%right.copy = call ptr @memcpy(ptr %%right.dst, ptr %%right.src, i64 %%right.copy.len)\n"
        "  %%null.offset = add i64 %%right.dst.offset, %%right.copy.len\n"
        "  %%null.ptr = getelementptr inbounds i8, ptr %%dst, i64 %%null.offset\n"
        "  store i8 0, ptr %%null.ptr\n"
        "  call void @cn_track_str(ptr %%dst)\n"
        "  ret ptr %%dst\n"
        "fallback:\n"
        "  %%empty.ptr = getelementptr inbounds [1 x i8], ptr @.cn.empty, i64 0, i64 0\n"
        "  ret ptr %%empty.ptr\n"
        "}\n\n",
        CN_LLVM_PATH_SEPARATOR
    );
    fputs(
        "define private ptr @cn_path_file_name(ptr %path) {\n"
        "entry:\n"
        "  %cursor.slot = alloca ptr\n"
        "  %start.slot = alloca ptr\n"
        "  store ptr %path, ptr %cursor.slot\n"
        "  store ptr %path, ptr %start.slot\n"
        "  br label %loop\n"
        "loop:\n"
        "  %cursor = load ptr, ptr %cursor.slot\n"
        "  %ch = load i8, ptr %cursor\n"
        "  %is.end = icmp eq i8 %ch, 0\n"
        "  br i1 %is.end, label %finish, label %check.sep\n"
        "check.sep:\n"
        "  %is.slash = icmp eq i8 %ch, 47\n"
        "  %is.backslash = icmp eq i8 %ch, 92\n"
        "  %is.sep = or i1 %is.slash, %is.backslash\n"
        "  br i1 %is.sep, label %mark.start, label %advance\n"
        "mark.start:\n"
        "  %next.start = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.start, ptr %start.slot\n"
        "  br label %advance\n"
        "advance:\n"
        "  %next.cursor = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.cursor, ptr %cursor.slot\n"
        "  br label %loop\n"
        "finish:\n"
        "  %start = load ptr, ptr %start.slot\n"
        "  %copy = call ptr @cn_dup_cstr(ptr %start)\n"
        "  ret ptr %copy\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private ptr @cn_path_stem(ptr %path) {\n"
        "entry:\n"
        "  %cursor.slot = alloca ptr\n"
        "  %start.slot = alloca ptr\n"
        "  %last.dot.slot = alloca ptr\n"
        "  store ptr %path, ptr %cursor.slot\n"
        "  store ptr %path, ptr %start.slot\n"
        "  store ptr null, ptr %last.dot.slot\n"
        "  br label %loop\n"
        "loop:\n"
        "  %cursor = load ptr, ptr %cursor.slot\n"
        "  %ch = load i8, ptr %cursor\n"
        "  %is.end = icmp eq i8 %ch, 0\n"
        "  br i1 %is.end, label %finish, label %check.sep\n"
        "check.sep:\n"
        "  %is.slash = icmp eq i8 %ch, 47\n"
        "  %is.backslash = icmp eq i8 %ch, 92\n"
        "  %is.sep = or i1 %is.slash, %is.backslash\n"
        "  br i1 %is.sep, label %mark.sep, label %check.dot\n"
        "mark.sep:\n"
        "  %next.start = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.start, ptr %start.slot\n"
        "  store ptr null, ptr %last.dot.slot\n"
        "  br label %advance\n"
        "check.dot:\n"
        "  %is.dot = icmp eq i8 %ch, 46\n"
        "  br i1 %is.dot, label %mark.dot, label %advance\n"
        "mark.dot:\n"
        "  store ptr %cursor, ptr %last.dot.slot\n"
        "  br label %advance\n"
        "advance:\n"
        "  %next.cursor = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.cursor, ptr %cursor.slot\n"
        "  br label %loop\n"
        "finish:\n"
        "  %start = load ptr, ptr %start.slot\n"
        "  %last.dot = load ptr, ptr %last.dot.slot\n"
        "  %has.dot = icmp ne ptr %last.dot, null\n"
        "  br i1 %has.dot, label %check.valid.dot, label %copy.full\n"
        "check.valid.dot:\n"
        "  %start.int = ptrtoint ptr %start to i64\n"
        "  %dot.int = ptrtoint ptr %last.dot to i64\n"
        "  %dot.at.start = icmp eq i64 %start.int, %dot.int\n"
        "  %after.dot = getelementptr inbounds i8, ptr %last.dot, i64 1\n"
        "  %after.dot.ch = load i8, ptr %after.dot\n"
        "  %dot.at.end = icmp eq i8 %after.dot.ch, 0\n"
        "  %dot.valid.start = xor i1 %dot.at.start, true\n"
        "  %dot.valid.end = xor i1 %dot.at.end, true\n"
        "  %dot.valid = and i1 %dot.valid.start, %dot.valid.end\n"
        "  br i1 %dot.valid, label %copy.range, label %copy.full\n"
        "copy.range:\n"
        "  %length = sub i64 %dot.int, %start.int\n"
        "  %stem = call ptr @cn_dup_range(ptr %start, i64 %length)\n"
        "  ret ptr %stem\n"
        "copy.full:\n"
        "  %full = call ptr @cn_dup_cstr(ptr %start)\n"
        "  ret ptr %full\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private ptr @cn_path_extension(ptr %path) {\n"
        "entry:\n"
        "  %cursor.slot = alloca ptr\n"
        "  %start.slot = alloca ptr\n"
        "  %last.dot.slot = alloca ptr\n"
        "  store ptr %path, ptr %cursor.slot\n"
        "  store ptr %path, ptr %start.slot\n"
        "  store ptr null, ptr %last.dot.slot\n"
        "  br label %loop\n"
        "loop:\n"
        "  %cursor = load ptr, ptr %cursor.slot\n"
        "  %ch = load i8, ptr %cursor\n"
        "  %is.end = icmp eq i8 %ch, 0\n"
        "  br i1 %is.end, label %finish, label %check.sep\n"
        "check.sep:\n"
        "  %is.slash = icmp eq i8 %ch, 47\n"
        "  %is.backslash = icmp eq i8 %ch, 92\n"
        "  %is.sep = or i1 %is.slash, %is.backslash\n"
        "  br i1 %is.sep, label %mark.sep, label %check.dot\n"
        "mark.sep:\n"
        "  %next.start = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.start, ptr %start.slot\n"
        "  store ptr null, ptr %last.dot.slot\n"
        "  br label %advance\n"
        "check.dot:\n"
        "  %is.dot = icmp eq i8 %ch, 46\n"
        "  br i1 %is.dot, label %mark.dot, label %advance\n"
        "mark.dot:\n"
        "  store ptr %cursor, ptr %last.dot.slot\n"
        "  br label %advance\n"
        "advance:\n"
        "  %next.cursor = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.cursor, ptr %cursor.slot\n"
        "  br label %loop\n"
        "finish:\n"
        "  %start = load ptr, ptr %start.slot\n"
        "  %last.dot = load ptr, ptr %last.dot.slot\n"
        "  %has.dot = icmp ne ptr %last.dot, null\n"
        "  br i1 %has.dot, label %check.valid.dot, label %return.empty\n"
        "check.valid.dot:\n"
        "  %start.int = ptrtoint ptr %start to i64\n"
        "  %dot.int = ptrtoint ptr %last.dot to i64\n"
        "  %dot.at.start = icmp eq i64 %start.int, %dot.int\n"
        "  %after.dot = getelementptr inbounds i8, ptr %last.dot, i64 1\n"
        "  %after.dot.ch = load i8, ptr %after.dot\n"
        "  %dot.at.end = icmp eq i8 %after.dot.ch, 0\n"
        "  %dot.valid.start = xor i1 %dot.at.start, true\n"
        "  %dot.valid.end = xor i1 %dot.at.end, true\n"
        "  %dot.valid = and i1 %dot.valid.start, %dot.valid.end\n"
        "  br i1 %dot.valid, label %return.ext, label %return.empty\n"
        "return.ext:\n"
        "  %ext = call ptr @cn_dup_cstr(ptr %after.dot)\n"
        "  ret ptr %ext\n"
        "return.empty:\n"
        "  %empty = call ptr @cn_dup_range(ptr %path, i64 0)\n"
        "  ret ptr %empty\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private i1 @cn_path_is_absolute(ptr %path) {\n"
        "entry:\n"
        "  %first = load i8, ptr %path\n"
        "  %is.slash = icmp eq i8 %first, 47\n"
        "  %is.backslash = icmp eq i8 %first, 92\n"
        "  %is.sep = or i1 %is.slash, %is.backslash\n"
        "  br i1 %is.sep, label %return.true, label %check.drive\n"
        "check.drive:\n"
        "  %upper.low = icmp uge i8 %first, 65\n"
        "  %upper.high = icmp ule i8 %first, 90\n"
        "  %upper = and i1 %upper.low, %upper.high\n"
        "  %lower.low = icmp uge i8 %first, 97\n"
        "  %lower.high = icmp ule i8 %first, 122\n"
        "  %lower = and i1 %lower.low, %lower.high\n"
        "  %is.alpha = or i1 %upper, %lower\n"
        "  br i1 %is.alpha, label %check.colon, label %return.false\n"
        "check.colon:\n"
        "  %second.ptr = getelementptr inbounds i8, ptr %path, i64 1\n"
        "  %second = load i8, ptr %second.ptr\n"
        "  %is.colon = icmp eq i8 %second, 58\n"
        "  br i1 %is.colon, label %check.third, label %return.false\n"
        "check.third:\n"
        "  %third.ptr = getelementptr inbounds i8, ptr %path, i64 2\n"
        "  %third = load i8, ptr %third.ptr\n"
        "  %third.slash = icmp eq i8 %third, 47\n"
        "  %third.backslash = icmp eq i8 %third, 92\n"
        "  %third.sep = or i1 %third.slash, %third.backslash\n"
        "  ret i1 %third.sep\n"
        "return.true:\n"
        "  ret i1 true\n"
        "return.false:\n"
        "  ret i1 false\n"
        "}\n\n",
        stream
    );
    fputs(
        "define private { i1, ptr } @cn_path_parent(ptr %path) {\n"
        "entry:\n"
        "  %cursor.slot = alloca ptr\n"
        "  %last.sep.slot = alloca ptr\n"
        "  store ptr %path, ptr %cursor.slot\n"
        "  store ptr null, ptr %last.sep.slot\n"
        "  br label %loop\n"
        "loop:\n"
        "  %cursor = load ptr, ptr %cursor.slot\n"
        "  %ch = load i8, ptr %cursor\n"
        "  %is.end = icmp eq i8 %ch, 0\n"
        "  br i1 %is.end, label %finish, label %check.sep\n"
        "check.sep:\n"
        "  %is.slash = icmp eq i8 %ch, 47\n"
        "  %is.backslash = icmp eq i8 %ch, 92\n"
        "  %is.sep = or i1 %is.slash, %is.backslash\n"
        "  br i1 %is.sep, label %mark.sep, label %advance\n"
        "mark.sep:\n"
        "  store ptr %cursor, ptr %last.sep.slot\n"
        "  br label %advance\n"
        "advance:\n"
        "  %next.cursor = getelementptr inbounds i8, ptr %cursor, i64 1\n"
        "  store ptr %next.cursor, ptr %cursor.slot\n"
        "  br label %loop\n"
        "finish:\n"
        "  %last.sep = load ptr, ptr %last.sep.slot\n"
        "  %has.sep = icmp ne ptr %last.sep, null\n"
        "  br i1 %has.sep, label %copy.parent, label %return.err\n"
        "copy.parent:\n"
        "  %path.int = ptrtoint ptr %path to i64\n"
        "  %sep.int = ptrtoint ptr %last.sep to i64\n"
        "  %length = sub i64 %sep.int, %path.int\n"
        "  %is.root = icmp eq i64 %length, 0\n"
        "  br i1 %is.root, label %copy.root, label %copy.range\n"
        "copy.root:\n"
        "  %root.copy = call ptr @cn_dup_range(ptr %path, i64 1)\n"
        "  br label %return.ok.root\n"
        "return.ok.root:\n"
        "  %ok.root = insertvalue { i1, ptr } zeroinitializer, i1 true, 0\n"
        "  %value.root = insertvalue { i1, ptr } %ok.root, ptr %root.copy, 1\n"
        "  ret { i1, ptr } %value.root\n"
        "copy.range:\n"
        "  %parent.copy = call ptr @cn_dup_range(ptr %path, i64 %length)\n"
        "  %ok = insertvalue { i1, ptr } zeroinitializer, i1 true, 0\n"
        "  %value.ok = insertvalue { i1, ptr } %ok, ptr %parent.copy, 1\n"
        "  ret { i1, ptr } %value.ok\n"
        "return.err:\n"
        "  ret { i1, ptr } zeroinitializer\n"
        "}\n\n",
        stream
    );
}
